app:
  name: ads
db:
  adapter: postgresql
  host: localhost
  user: postgres
  url: <%= ENV['ADS_DATABASE_URL'] %>
pagination:
  page_size: 10
rabbit_mq:
  host: <%= ENV['RABBITMQ_HOST'] %>
  username: <%= ENV['RABBITMQ_USER'] %>
  password: <%= ENV['RABBITMQ_PASSWORD'] %> 
  consumer_pool: 10
logger:
  path: log/app.log
  level: info
